
title: dcf's blog
tagline: 蛋炒饭是什么鬼
email: dcf_xyz@outlook.com
description: 
  じ★ve莪вμ绘⒋個fёΙ惣妑，вμ绘妑вμ绘妑↗
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dcfxyz
permalink: /:year/:month/:day/:title.html

author:
  name: fcnaud
  url: 
  email: dcf_xyz@outlook.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# valine comment
valine_comment:
  enable: true
  leancloud_appid: "85hI164K99KDELgzdwNsLnJ8-gzGzoHsz"
  leancloud_appkey: "QYSYhcK7gsN0xb5uimwYNIll"
  placeholder: "说点什么……"

paginate: 10
